name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          ROOT_FOLDER=$(pwd)
          
          sudo apt install libmicrohttpd-dev
          
          cd lib
          make
          
          cd prom
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ..
          cd ..
          
          cd promhttp
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ROOT_FOLDER
          
          mkdir build
          cd build
          cmake ..
          make all
