name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          sudo apt install libmicrohttpd-dev
          cd lib
          make
          cd prom
          mkdir -p build
          cd build
          cmake ..
          make
          sudo make install
          cd ..
          cd ..
          
          cd promhttp
          mkdir -p build
          cd build
          cmake ..
          make
          sudo make install
          cd ROOT_FOLDER
          mkdir -p build
          cd build
          cmake ..
          make all
